# Generated by Django 4.2.6 on 2023-10-26 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeRole',
            new_name='Employee_Role',
        ),
    ]
