# Generated by Django 4.2.6 on 2023-10-31 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_role_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_clock_in',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='employee_clock_in',
            name='is_am',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employee_clock_in',
            name='tipout_received',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
