# Generated by Django 4.2.6 on 2023-10-31 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_employee_clock_in_date_employee_clock_in_is_am_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout_Tipout_Breakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('checkout_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.checkout')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.role')),
            ],
        ),
        migrations.AddField(
            model_name='checkout',
            name='support_roles',
            field=models.ManyToManyField(related_name='checkouts', through='api.Checkout_Tipout_Breakdown', to='api.role'),
        ),
    ]
