# Generated by Django 4.2.6 on 2023-11-01 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_checkout_tipout_breakdown_checkout_support_roles'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee_clock_in',
            unique_together={('employee_id', 'date', 'is_am')},
        ),
    ]
