# Generated by Django 4.2.6 on 2023-11-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_employee_clock_in_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='total_tipout',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
