# Generated by Django 4.2.6 on 2023-11-05 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_tipout_formula_max_tipout_tipout_formula_min_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipout_formula',
            name='is_time_based',
            field=models.BooleanField(default=True),
        ),
    ]
