# Generated by Django 4.2.6 on 2023-11-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_checkout_is_am_shift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipout_formula',
            name='is_time_based',
            field=models.BooleanField(default=True),
        ),
    ]
