# Generated by Django 4.2.6 on 2023-11-05 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_checkout_tipout_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout_tipout_breakdown',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout_tipout_breakdown',
            name='is_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkout_tipout_breakdown',
            name='sheet_cell',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='checkout_tipout_breakdown',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
