# Generated by Django 4.2.6 on 2023-11-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_checkout_tipout_breakdown_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='total_owed',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
