# Generated by Django 4.2.6 on 2023-11-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_employee_clock_in_is_bar_role_is_bar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='is_bar',
            field=models.BooleanField(),
        ),
    ]
